---
driver_plugin: vagrant
driver_config:
  customize:
    cpus: 2
    memory: 512
  ssh:
    insert_key: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 12.16.42
  log_level: info
  log_file: /var/log/chef-solo.log

platforms:
- name: centos-6.8
  run_list: ['recipe[fake::create_secrets]','recipe[yum-epel]']
  driver_config:
    box: bento/centos-6.8
- name: centos-7.2
  run_list: ['recipe[fake::create_secrets]','recipe[yum-epel]']
  driver_config:
    box: bento/centos-7.2
#- name: rhel-6.5
#  run_list: ['recipe[yum-epel]', 'recipe[rhsm]']
#  attributes:
#    rhsm:
#      username: <%= ENV['RHSM_USERNAME'] %>
#      password: <%= ENV['RHSM_PASSWORD'] %>
#      compile_time: true
#      additional_repos: ['rhel-6-server-optional-rpms']
#  driver_config:
#    box: local-rhel-6.5
#    box_url: file://<%= File.expand_path('~') %>/opscode_rhel-6.5_chef-provisionerless.box
- name: ubuntu-12.04
  run_list: ['recipe[fake::create_secrets]','recipe[apt]']
  driver_config:
    box: bento/ubuntu-12.04
- name: ubuntu-14.04
  run_list: ['recipe[fake::create_secrets]','recipe[apt]']
  driver_config:
    box: bento/ubuntu-14.04

suites:
- name: default
  run_list:
  - recipe[rs-mysql::default]
  - recipe[rs-mysql::collectd]
  - recipe[fake::database_mysql]
  attributes:
    apt:
      compile_time_update: true
    cloud:
      provider: 'vagrant'
      public_ips: ['100.64.1.1']
      private_ips: ['10.0.2.15']
    rs-base:
      collectd_server: 'tss-4.rightscale.com'
    rs-mysql:
      backup:
        lineage: 'lineage'
      mysql:
        version: '5.6'
      server_root_password: rootpass
      server_repl_password: realpass
      server_usage: dedicated
      application_username: appuser
      application_password: apppass
      application_database_name: app_test
    rightscale:
      instance_uuid: '1111111'

- name: empty_public_ips
  run_list:
  - recipe[rs-mysql::default]
  - recipe[rs-mysql::collectd]
  - recipe[fake::database_mysql]
  attributes:
    apt:
      compile_time_update: true
    cloud:
      provider: 'vagrant'
      public_ips: ['']
      private_ips: ['10.0.2.15']
    rs-base:
      collectd_server: 'tss-4.rightscale.com'
    rs-mysql:
      backup:
        lineage: 'lineage'
      server_root_password: rootpass
      server_repl_password: realpass
      server_usage: dedicated
      application_username: appuser
      application_password: apppass
      application_database_name: app_test
      import:
        repository: https://github.com/rightscale/examples.git
        revision: unified_php
    rightscale:
      instance_uuid: '1111111'

- name: shared_server
  run_list:
  - recipe[rs-mysql::default]
  - recipe[fake::database_mysql]
  attributes:
    apt:
      compile_time_update: true
    cloud:
      provider: 'vagrant'
      public_ips: ['100.64.1.1']
      private_ips: ['10.0.2.15']
    rs-base:
      collectd_server: 'tss-4.rightscale.com'
    rs-mysql:
      backup:
        lineage: 'lineage'
      server_root_password: rootpass
      server_repl_password: replpass
      server_usage: shared
      application_database_name: app_test


- name: master
  run_list:
  - recipe[rs-mysql::master]
  attributes:
    apt:
      compile_time_update: true
    cloud:
      provider: 'vagrant'
      public_ips: ['100.64.1.1']
      private_ips: ['10.0.2.15']
    rs-base:
      collectd_server: 'tss-4.rightscale.com'
    rs-mysql:
      backup:
        lineage: 'lineage'
      server_root_password: rootpass
      server_repl_password: replpass
      server_usage: dedicated
    rightscale:
      instance_uuid: '1111111'

- name: slave
  run_list:
  - recipe[fake::master]
  - recipe[rs-mysql::slave]
  attributes:
    apt:
      compile_time_update: true
    cloud:
      provider: 'vagrant'
      public_ips: ['100.64.2.2']
      private_ips: ['10.0.2.15']
    rs-base:
      collectd_server: 'tss-4.rightscale.com'
    rs-mysql:
      backup:
        lineage: 'lineage'
      server_root_password: rootpass
      server_repl_password: replpass
      server_usage: dedicated
      slave_functional_timeout: -1
    rightscale:
      instance_uuid: '2222222'
